import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ButtonPrimary from "@/components/ButtonPrimary";
import ButtonSecondary from "@/components/ButtonSecondary";
import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";

export default function ChildQuestions({question, onSelect}) {
  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
                <Navbar />
                <div>
                  <h2>{question}</h2>
                  <button onClick={() => onSelect("Option Awful")}>Awful</button>
                  <button onClick={() => onSelect("Option Bad")}>Bad</button>
                  <button onClick={() => onSelect("Option Decent")}>Decent</button>
                  <button onClick={() => onSelect("Option Good")}>Good</button>
                  <button onClick={() => onSelect("Option E")}>Amazing</button>
    </div>
                <Tabbar />
        </div>
      </main>
    </>
  );
}