import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function ChildQuestions({ question, onSelect, previousAnswer }) {
  const [selectedOption, setSelectedOption] = useState(null);

  const handleOptionSelect = (option) => {
    setSelectedOption(option);
    onSelect(option);
  };

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        {/* <div className={styles.mainContainer}> */}
          <h2>{question}</h2>
          {question === "Question 1" && (
            <>
              <label>
                <input
                  type="radio"
                  value="Awful"
                  checked={selectedOption === "Awful"}
                  onChange={() => handleOptionSelect("Awful")}
                />
                Awful
              </label>
              <label>
                <input
                  type="radio"
                  value="Bad"
                  checked={selectedOption === "Bad"}
                  onChange={() => handleOptionSelect("Bad")}
                />
                Bad
              </label>
              <label>
                <input
                  type="radio"
                  value="Decent"
                  checked={selectedOption === "Decent"}
                  onChange={() => handleOptionSelect("Decent")}
                />
                Decent
              </label>
              <label>
                <input
                  type="radio"
                  value="Good"
                  checked={selectedOption === "Good"}
                  onChange={() => handleOptionSelect("Good")}
                />
                Good
              </label>
              <label>
                <input
                  type="radio"
                  value="Amazing"
                  checked={selectedOption === "Amazing"}
                  onChange={() => handleOptionSelect("Amazing")}
                />
                Amazing
              </label>
            </>
          )}
          {question === "Question 2" && (
            <>
              <label>
                <input
                  type="radio"
                  value="Joy"
                  checked={selectedOption === "Joy"}
                  onChange={() => handleOptionSelect("Joy")}
                />
                Joy
              </label>
              <label>
                <input
                  type="radio"
                  value="Sadness"
                  checked={selectedOption === "Sadness"}
                  onChange={() => handleOptionSelect("Sadness")}
                />
                Sadness
              </label>
              <label>
                <input
                  type="radio"
                  value="Fear"
                  checked={selectedOption === "Fear"}
                  onChange={() => handleOptionSelect("Fear")}
                />
                Fear
              </label>
              <label>
                <input
                  type="radio"
                  value="Anger"
                  checked={selectedOption === "Anger"}
                  onChange={() => handleOptionSelect("Anger")}
                />
                Anger
              </label>
            </>
          )}
          {question === "Question 3" && previousAnswer === "Joy" && (
            <>
              <label>
                <input
                  type="checkbox"
                  value="Happy"
                  checked={selectedOption === "Happy"}
                  onChange={() => handleOptionSelect("Happy")}
                />
                Happy
              </label>
              <label>
                <input
                  type="checkbox"
                  value="Optimistic"
                  checked={selectedOption === "Optimistic"}
                  onChange={() => handleOptionSelect("Optimistic")}
                />
                Optimistic
              </label>
              {/* Add more options for Joy */}
            </>
          )}
          {question === "Question 3" && previousAnswer === "Sadness" && (
            <>
              <label>
                <input
                  type="checkbox"
                  value="Grief"
                  checked={selectedOption === "Grief"}
                  onChange={() => handleOptionSelect("Grief")}
                />
                Grief
              </label>
              <label>
                <input
                  type="checkbox"
                  value="Lonely"
                  checked={selectedOption === "Lonely"}
                  onChange={() => handleOptionSelect("Lonely")}
                />
                Lonely
              </label>
              {/* Add more options for Sadness */}
            </>
          )}
          {/* Add similar logic for Fear and Anger */}
          {question === "Question 4" && (
            <>
              <label>
                <input
                  type="radio"
                  value="Work"
                  checked={selectedOption === "Work"}
                  onChange={() => handleOptionSelect("Work")}
                />
                Work
              </label>
              <label>
                <input
                  type="radio"
                  value="Family"
                  checked={selectedOption === "Family"}
                  onChange={() => handleOptionSelect("Family")}
                />
                Family
              </label>
              <label>
                <input
                  type="radio"
                  value="School"
                  checked={selectedOption === "School"}
                  onChange={() => handleOptionSelect("School")}
                />
                School
              </label>
              <label>
                <input
                  type="radio"
                  value="Relationships"
                  checked={selectedOption === "Relationships"}
                  onChange={() => handleOptionSelect("Relationships")}
                />
                Relationships
              </label>
            </>
          )}
        {/* </div> */}
      </main>
    </>
  );
}
