import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import { useState } from "react";
import Layout from "@/components/Layout";

export default function ChildQuestions({ question, onSelect, previousAnswer, handleNextStep }) {
  const [selectedOption, setSelectedOption] = useState(null);
  const [selectedOptions, setSelectedOptions] = useState([]);

  const handleOptionSelect = (option) => {
    setSelectedOption(option);
    onSelect(option);
  };

  const handleMultiSelect = (option) => {
    const updatedOptions = selectedOptions.includes(option)
      ? selectedOptions.filter((selectedOption) => selectedOption !== option)
      : [...selectedOptions, option];
    setSelectedOptions(updatedOptions);
    onSelect(updatedOptions);
  };

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
          <Layout>
            <h2 className={styles.question}>{question}</h2>
            <div className={styles.optionsContainer}>
              {question === "How are you today?" && (
                <div className={styles.emojis}>
                  <ImageOption
                    src="/images/emojis/awful.svg"
                    alt="Awful"
                    selected={selectedOption === "Awful"}
                    onClick={() => handleOptionSelect("Awful")}
                  />
                  {/* Add other ImageOption components for different options */}
                </div>
              )}
              {question === "How do you feel?" && (
                <div className={styles.emojisEmotion}>
                  <EmotionOption
                    src="/images/emotions/joy.svg"
                    alt="Joy"
                    selected={selectedOption === "Joy"}
                    onClick={() => handleOptionSelect("Joy")}
                  />
                  {/* Add other EmotionOption components for different options */}
                </div>
              )}
              {question === "Describe your feelings?" && previousAnswer && (
                <div className={styles.multiSelectContainer}>
                  <h3>Tap any words that best describe how you are feeling</h3>
                  <div className={styles.wordOptions}>
                    <WordOption
                      word="Happy"
                      selected={selectedOptions.includes("Happy")}
                      onClick={() => handleMultiSelect("Happy")}
                    />
                    {/* Add other WordOption components for different options */}
                  </div>
                </div>
              )}
              {question === "What's taking up most of your headspace right now?" && (
                <div className={styles.emojisEmotion}>
                  <HeadSpaceOption
                    src="/images/headspace/work.svg"
                    alt="Work"
                    selected={selectedOption === "Work"}
                    onClick={() => handleOptionSelect("Work")}
                  />
                  {/* Add other HeadSpaceOption components for different options */}
                </div>
              )}
            </div>
            <div className={styles.buttonContainer}>
              <button className={styles.secondaryButton} onClick={handleNextStep}>Next</button>
            </div>
          </Layout>
        </div>
      </main>
    </>
  );
}

function ImageOption({ src, alt, selected, onClick }) {
  return (
    <div className={`${styles.option} ${selected && styles.selected}`} onClick={onClick}>
      <Image src={src} alt={alt} width={80} height={80} />
    </div>
  );
}

function EmotionOption({ src, alt, selected, onClick }) {
  return (
    <div className={`${styles.option} ${selected && styles.selected}`} onClick={onClick}>
      <Image src={src} alt={alt} width={100} height={100} />
    </div>
  );
}

function WordOption({ word, selected, onClick }) {
  return (
    <div className={`${styles.wordOption} ${selected && styles.selected}`} onClick={onClick}>
      {word}
    </div>
  );
}

function HeadSpaceOption({ src, alt, selected, onClick }) {
  return (
    <div className={`${styles.option} ${selected && styles.selected}`} onClick={onClick}>
      <Image src={src} alt={alt} width={100} height={100} />
    </div>
  );
}
