// ChildQuestions.js
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Image from "next/image";

export default function ChildQuestions({ question, onSelect, previousAnswer, handleNextStep }) {
  const [selectedOption, setSelectedOption] = useState(null);

  const handleOptionSelect = (option) => {
    setSelectedOption(option);
    onSelect(option);
  };

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
          <h2>{question}</h2>
          {question === "How are you today?" && (
            <>
              <div className={styles.emojis}>
                <Image
                  src="/images/emojis/awful.svg"
                  alt="Awful"
                  width={80}
                  height={80}
                  className={selectedOption === "Awful" ? styles.selected : styles.unselected}
                  onClick={() => handleOptionSelect("Awful")}
                />
                <Image
                  src="/images/emojis/bad.svg"
                  alt="Bad"
                  width={80}
                  height={80}
                  className={selectedOption === "Bad" ? styles.selected : styles.unselected}
                  onClick={() => handleOptionSelect("Bad")}
                />
                {/* Add similar Image components for other options */}
              </div>
            </>
          )}
          {/* Add similar logic for other questions */}
        </div>
      </main>
    </>
  );
}
