import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

export default function ChildQuestions({ question, onSelect, previousAnswer }) {
  const [selectedOption, setSelectedOption] = useState(null);

  const handleOptionSelect = (option) => {
    setSelectedOption(option);
    onSelect(option);
  };

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
          <h2>{question}</h2>
          {question === "Question 1" && (
            <>
              <label>
                <input
                  type="radio"
                  value="Awful"
                  checked={selectedOption === "Awful"}
                  onChange={() => handleOptionSelect("Awful")}
                />
                Awful
              </label>
              <label>
                <input
                  type="radio"
                  value="Bad"
                  checked={selectedOption === "Bad"}
                  onChange={() => handleOptionSelect("Bad")}
                />
                Bad
              </label>
              <label>
                <input
                  type="radio"
                  value="Decent"
                  checked={selectedOption === "Decent"}
                  onChange={() => handleOptionSelect("Decent")}
                />
                Decent
              </label>
              <label>
                <input
                  type="radio"
                  value="Good"
                  checked={selectedOption === "Good"}
                  onChange={() => handleOptionSelect("Good")}
                />
                Good
              </label>
              <label>
                <input
                  type="radio"
                  value="Amazing"
                  checked={selectedOption === "Amazing"}
                  onChange={() => handleOptionSelect("Amazing")}
                />
                Amazing
              </label>
            </>
          )}
          {question === "Question 2" && (
            <>
              {/* Similar radio input logic for question 2 */}
            </>
          )}
          {question === "Question 3" && previousAnswer && (
            <>
              {/* Similar radio input logic for question 3 */}
            </>
          )}
          {question === "Question 4" && (
            <>
              {/* Similar radio input logic for question 4 */}
            </>
          )}
          <button onClick={handleNextStep}>Next</button>
        </div>
      </main>
    </>
  );
}
