import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";
import { useState } from "react";

export default function ChildQuestions({ question, onSelect, previousAnswer, handleNextStep }) {
  const [selectedOption, setSelectedOption] = useState(null);
  const [isClicked, setIsClicked] = useState(false);

  const handleOptionSelect = (option) => {
    setSelectedOption(option);
    setIsClicked(true);
    onSelect(option);
  };

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
          <Navbar />
          <h2 className={styles.questionOne}>{question}</h2>
          {question === "How are you today?" && (
            <>
               <div className={styles.emojis}>
                <div className={styles.emojisBold}>
                  <Image
                    src={selectedOption === "Awful" ? "/images/bold-emojis/bawful.svg" : "/images/emojis/awful.svg"}
                    alt="Awful"
                    width={isClicked && selectedOption === "Awful" ? 90 : 80}
                    height={isClicked && selectedOption === "Awful" ? 90 : 80}
                    onClick={() => handleOptionSelect("Awful")}
                  />
                  <Image
                    src={selectedOption === "Bad" ? "/images/bold-emojis/bbad.svg" : "/images/emojis/bad.svg"}
                    alt="Bad"
                    width={isClicked && selectedOption === "Awful" ? 90 : 80}
                    height={isClicked && selectedOption === "Awful" ? 90 : 80}
                    onClick={() => handleOptionSelect("Bad")}
                  />
                  <Image
                    src={selectedOption === "Decent" ? "/images/bold-emojis/bdecent.svg" : "/images/emojis/decent.svg"}
                    alt="Decent"
                    width={isClicked && selectedOption === "Awful" ? 90 : 80}
                    height={isClicked && selectedOption === "Awful" ? 90 : 80}
                    onClick={() => handleOptionSelect("Decent")}
                  />
                  <Image
                    src={selectedOption === "Good" ? "/images/bold-emojis/bgood.svg" : "/images/emojis/good.svg"}
                    alt="Good"
                    width={isClicked && selectedOption === "Awful" ? 90 : 80}
                    height={isClicked && selectedOption === "Awful" ? 90 : 80}
                    onClick={() => handleOptionSelect("Good")}
                  />
                  <Image
                    src={selectedOption === "Amazing" ? "/images/bold-emojis/bamazing.svg" : "/images/emojis/amazing.svg"}
                    alt="Amazing"
                    width={isClicked && selectedOption === "Amazing" ? 90 : 80}
                    height={isClicked && selectedOption === "Amazing" ? 90 : 80}
                    onClick={() => handleOptionSelect("Amazing")}
                  />
                </div>
              </div>
            </>
          )}
          {question === "How do you feel?" && (
            <>
              <div className={styles.questionDescription}>Which emotion do you feel most intensely?</div>
              <label>
                <input
                  type="radio"
                  value="Joy"
                  checked={selectedOption === "Joy"}
                  onChange={() => handleOptionSelect("Joy")}
                />
                Joy
              </label>
              <label>
                <input
                  type="radio"
                  value="Sadness"
                  checked={selectedOption === "Sadness"}
                  onChange={() => handleOptionSelect("Sadness")}
                />
                Sadness
              </label>
              <label>
                <input
                  type="radio"
                  value="Fear"
                  checked={selectedOption === "Fear"}
                  onChange={() => handleOptionSelect("Fear")}
                />
                Fear
              </label>
              <label>
                <input
                  type="radio"
                  value="Anger"
                  checked={selectedOption === "Anger"}
                  onChange={() => handleOptionSelect("Anger")}
                />
                Anger
              </label>
            </>
          )}
          {question === "Describe your feelings?" && previousAnswer && (
            <>
              <label>
                <input
                  type="checkbox"
                  value="Happy"
                  checked={selectedOptions.includes("Happy")}
                  onChange={() => handleOptionSelect("Happy")}
                />
                Happy
              </label>
              <label>
                <input
                  type="checkbox"
                  value="Optimistic"
                  checked={selectedOptions.includes("Optimistic")}
                  onChange={() => handleOptionSelect("Optimistic")}
                />
                Optimistic
              </label>
              <label>
                <input
                  type="checkbox"
                  value="Excited"
                  checked={selectedOptions.includes("Excited")}
                  onChange={() => handleOptionSelect("Excited")}
                />
                Excited
              </label>
            </>
          )}
          {question === "What’s taking up most of your headspace right now?" && (
            <>
                <div className={styles.emojis}>
                  <Image
                    src={selectedOption === "Work" ? styles.selectedHeadspace : "/images/headspace/work.svg"}
                    alt="Work"
                    width={80}
                    height={80}
                    onClick={() => handleOptionSelect("Work")}
                  />
                  <div className={styles.headspaceText}>Work</div>
                </div>
                <div className={styles.emojis}>
                  <Image
                    src={selectedOption === "Family" ? styles.selectedHeadspace : "/images/headspace/house.svg"}
                    alt="Family"
                    width={80}
                    height={80}
                    onClick={() => handleOptionSelect("Family")}
                  />
                  <div className={styles.headspaceText}>Family</div>
                </div>
                <div className={styles.emojis}>
                  <Image
                    src={selectedOption === "School" ? styles.selectedHeadspace : "/images/headspace/school.svg"}
                    alt="School"
                    width={80}
                    height={80}
                    onClick={() => handleOptionSelect("School")}
                  />
                  <div className={styles.headspaceText}>School</div>
                </div>
                <div className={styles.emojis}>
                  <Image
                    src={selectedOption === "Relationships" ? styles.selectedHeadspace :  "/images/headspace/relationships.svg"}
                    alt="Relationships"
                    width={80}
                    height={80}
                    onClick={() => handleOptionSelect("Relationships")}
                  />
                  <div className={styles.headspaceText}>Relationships</div>
                </div>
            </>
          )}
        <Tabbar />
        </div>
      </main>
    </>
  );
}