import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Button from "@/components/ButtonPrimary";
import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";

export default function Home() {
  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
          



        </div>
        
      </main>
    </>
  );
}
