import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ButtonPrimary from "@/components/ButtonPrimary";
import ButtonSecondary from "@/components/ButtonSecondary";
import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";

export default function Onboarding() {
  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
        <h className={styles.GetStarted}>
      <div className={styles.ImagePlaceholder}>
        <div className={styles.Rectangle1} />
        <div className={styles.Line1}></div>
        <div className={styles.Line2}></div>
      </div>
      <div className={styles.Calmquest}>CalmQuest</div>
      <div className={styles.ButtonLarge}>
        <div className={styles.Button}>Get Started</div>
      </div>
    </div>



        </div>
        
      </main>
    </>
  );
}
