import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ButtonPrimary from "@/components/ButtonPrimary";
import ButtonSecondary from "@/components/ButtonSecondary";
import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";
import Image from "next/image";
import { useEffect } from "react";

export default function Onboarding() {
  const LoadingScreen = () => {
    const [isLoading, setIsLoading] = useState(true);
  
    // Simulating a 3-second loading time
    useEffect(() => {
      const timer = setTimeout(() => {
        setIsLoading(false);
      }, 3000);
  
      return () => clearTimeout(timer);
    }, []);
  }
  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
        <Image
            src={`/images/placeholder.svg`}
            alt="logo"
            width={190}
            height={190}
            className={styles.logo}
          />
        <h1 className={styles.title}>CalmQuest</h1>



        </div>
        
      </main>
    </>
  );
}
