// ParentQuiz.js
import Head from "next/head";
import styles from "@/styles/Home.module.css";
import { useState } from "react";
import Link from "next/link";
import ChildQuestions from "./ChildQuestions";

export default function ParentQuiz() {
  const [step, setStep] = useState(1);
  const [previousAnswer, setPreviousAnswer] = useState(null);
  const [selectedAnswers, setSelectedAnswers] = useState([]);
  const [quizComplete, setQuizComplete] = useState(false);
  const [score, setScore] = useState(0);
  const [message, setMessage] = useState("");

  const handleAnswerSelect = (answer, points) => {
    setSelectedAnswers([...selectedAnswers, { answer, points }]);
    setScore(score + points);
    setPreviousAnswer(answer);
  };

  const handleNextStep = () => {
    if (step < 4) {
      setStep(step + 1);
    } else {
      setQuizComplete(true);
      sendFeedbackMessage();
    }
  };

  const sendFeedbackMessage = () => {
    if (score >= 0 && score <= 3) {
      setMessage("You are doing a great job! Keep it up and you'll do wonders!");
    } else if (score > 3 && score <= 6) {
      setMessage("You are doing great about your headspace!");
    } else if (score > -7 && score <= -5.5) {
      setMessage("It seems like you could benefit from professional help services. Please consider reaching out to them.");
    } else if (score > -5 && score <= -3) {
      setMessage("Encouraging message and redirection towards mental exercises.");
    } else if (score > -2.5 && score <= -0.5) {
      setMessage("Encouraging message and redirection towards mental exercises.");
    }
  };

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
          <ChildQuestions
            question={`Question ${step}`}
            onSelect={handleAnswerSelect}
            previousAnswer={previousAnswer}
            handleNextStep={handleNextStep} // Pass handleNextStep as a prop
          />
          {quizComplete ? (
            <>
              <p>{message}</p>
              <button>Claim Reward</button>
            </>
          ) : (
            <button onClick={handleNextStep}>Next</button>
          )}
        </div>
      </main>
    </>
  );
}
