import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ButtonPrimary from "@/components/ButtonPrimary";
import ButtonSecondary from "@/components/ButtonSecondary";
import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";
import ChildQuestions from "./ChildQuestions";

export default function ParentQuiz() {
  const [step, setStep] = useState(1);
  const [previousAnswer, setPreviousAnswer] = useState(null);
  const [selectedAnswers, setSelectedAnswers] = useState([]);
  const [quizComplete, setQuizComplete] = useState(false);
  const [score, setScore] = useState(0);

  const handleAnswerSelect = (answer, points) => {
    setSelectedAnswers([...selectedAnswers, { answer, points }]);
    setScore(score + points);
    setPreviousAnswer(answer);
  };

  const handleMultiSelect = (selectedOptions) => {
    let points = 0;
    // Adjust points based on the selected options (Add your logic here)
    // Example:
    selectedOptions.forEach((option) => {
      if (option === "Happy" || option === "Optimistic") {
        points += 0.5;
      } else if (option === "Grief" || option === "Lonely") {
        points -= 0.5;
      } // Add similar logic for other options
    });
    setSelectedAnswers([...selectedAnswers, { answer: selectedOptions, points }]);
    setScore(score + points);
  };

  const handleNextStep = () => {
    if (step < 4) {
      setStep(step + 1);
    } else {
      setQuizComplete(true);
    }
  };
  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={styles.mainContainer}>
                <div>
                  <ChildQuestions question={questions[step - 1]} onSelect={handleAnswerSelect} />
                    {selectedAnswer && (
                      <Link href={`/question${step + 1}`}>
                        <Link onClick={handleNextStep}>Next</Link>
                      </Link>
                    )}
                </div>
        </div>
      </main>
    </>
  );
}