import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Tabbar from "@/components/Tabbar";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import ButtonLong from "@/components/ButtonLong";
import Link from "next/link";
import ButtonPrimary from "@/components/ButtonPrimary";

export default function ChangeAvatar() {
    return (
        <>
          <Head>
                <title>CalmQuest</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main}`}>
                <div className={styles.mainContainer}>
                    <Navbar/>
                        <Link href="/EditProfile">
                                <ButtonLong title="Save" className={styles.editProfileSaveButton}></ButtonLong>
                        </Link>
                        <Tabbar/>
                </div>
            </main>
        </>
    )
}