import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";
import Link from "next/link";
import styles from '@/styles/Home.module.css';
import Head from "next/head";


export default function Contact() {
    return(
        <>
            <Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <main className={`${styles.main}`}>
                <div className={styles.mainContainer}>
                <Navbar/>
                    <div className={styles.goBackContainer}>
                        <Link href="/About">
                            {/* <img src="/images/icons/left arrow.svg" className={styles.leftArrow}></img> */}
                            Go Back
                        </Link>
                        
                            <h2>Contact Us</h2><div className={styles.contactUs}>
                            <p>
                            We’re here to help and answer any questions you might have.
                            </p>
                        </div>
                    </div>
                <Tabbar/>
                </div>
            </main>
        </>
    );
}