import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Tabbar from "@/components/Tabbar";
import Navbar from "@/components/Navbar";
import ButtonSave from "@/components/ButtonSave";
import Link from "next/link";
import { useState, useEffect } from "react";
import Image from "next/image";
import ButtonProfile from "@/components/ButtonProfile";
import { useRouter } from "next/router";

export default function EditProfile() {
    const [name, setName] = useState('');
    const [chosenIcon, setChosenIcon] = useState('');
    const router = useRouter();
    
    useEffect(() => {
        const storedName = localStorage.getItem('inputName');
        const storedIcon = localStorage.getItem('chosenIcon');
        if (storedName && storedIcon) {
            setName(storedName);
            setChosenIcon(storedIcon);
        }
    }, []);

    const handleNameChange = (e) => {
        setName(e.target.value);
    };

    const handleSave = () => {
        localStorage.setItem('inputName', name);
        router.push('/Profile');
    };

    return (
        <>
            <Head>
                <title>CalmQuest</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <div className={styles.mainContainer}>
                    <Navbar />
                    <div className={styles.profileInformation}>Profile Information</div>
                    <div className={styles.profileIcon}>
                        {chosenIcon && 
                            <Image 
                                src={chosenIcon}
                                alt="Profile Icon" 
                                width="100" 
                                height="100"
                                className={styles.editIcon} 
                            />
                        }
                    </div>
                    <div className={styles.selectOptions}>
                        <Link href="/ChangeAvatar">
                            <ButtonProfile title="Select Avatar" className={styles.optionsButton}></ButtonProfile>
                        </Link>
                        <Link href="/ChangeFrame">
                            <ButtonProfile title="Select Frame" className={styles.optionsButton}></ButtonProfile>
                        </Link>
                    </div>
                    <div className={styles.nameHeading}>Name</div>
                    <input 
                        id="inputName" 
                        className={`${styles.nameInput} ${styles.editProfileNameInput}`}
                        type="text" 
                        placeholder="Enter new name" 
                        value={name}
                        onChange={handleNameChange}
                    />
                    <ButtonSave title="Save" className={styles.editProfileSaveButton} onClick={handleSave}></ButtonSave>
                    <Tabbar />
                </div>
            </main>
        </>
    );
}
