import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Image from "next/image";
import ButtonPrimary from "@/components/ButtonPrimary";
import { useState, useEffect } from "react";
import { useRouter } from "next/router";
import AnimationLogo from "@/components/AnimationLogo";
import ButtonLong from "@/components/ButtonLong";
import DottedProgressBar from "@/components/DottedProgressBar";

export default function Home() {
  const router = useRouter();
  const [inputName, setInputName] = useState('');
  const [nameValid, setNameValid] = useState('');
  const [chosenIcon, setChosenIcon] = useState("/images/onboarding/option3.svg");
  const [data, setData] = useState([]);
  const [showGetStartedButton, setShowGetStartedButton] = useState(false);
  const [step, setStep] = useState(0);

  useEffect(() => {
    const timer = setTimeout(() => {
      setShowGetStartedButton(true);
    }, 3000);

    return () => clearTimeout(timer);
  }, []);

  const handleInputChange = (e) => {
    setInputName(e.target.value.slice(0, 20));
    if (!e.target.value.trim()) {
      setNameValid('Please enter your name');
    } else {
      setNameValid('');
    }
  };

  const handleIconClick = (icon) => {
    setChosenIcon(icon);
  };

  const goClick = () => {
    if (!inputName.trim()) {
      setNameValid('Please enter your name');
    } else {
      setNameValid('');
      setStep(5);
    }
  };
  
  const perfectClick = () => {
    router.push({
      pathname: '/HomePage',
      query: { name: inputName, icon: chosenIcon },
    });
  }

  const startOnboarding = () => {
    setStep(1);
  }

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
        <div className={`${styles.mainContainer} ${styles.onboardingBackground}`}>
          {step === 0 && (
            <div className={styles.animationGetStarted}>
              <AnimationLogo />
              {showGetStartedButton && (
                <ButtonLong className={`${styles.getStartedButton}`} onClick={startOnboarding} title="Get Started"></ButtonLong>
              )}
            </div>
          )}
          {step > 0 && (
            <div className={styles.onboardingContent}>
              {step === 1 && (
                <>
                  <Image 
                    src={`/images/onboarding/personalize.svg`} 
                    alt="personalize icon" 
                    width={150} 
                    height={150} 
                    className={styles.featureIcons}
                  />
                  <h2 className={styles.features}>Personalize your experience</h2>
                  <p className={styles.featuresText}>Select and unlock special avatars <br /> and frames from completing daily <br />check-ins</p>
                  <DottedProgressBar currentStep={step} />
                  <ButtonLong className={styles.nextButton} onClick={() => setStep(2)} title="Next" />
                </>
              )}
              {step === 2 && (
                <>
                  <Image 
                    src={`/images/onboarding/calendar.svg`} 
                    alt="calendar icon" 
                    width={150} 
                    height={150} 
                    className={styles.featureIcons}
                  />
                  <h2 className={styles.features}>Check-In and Rewards</h2>
                  <p className={styles.featuresText}>Check in on your mental health <br /> and collect seeds to buy avatars <br /> and frames from the shop</p>
                  <DottedProgressBar currentStep={step} />
                  <ButtonLong className={styles.nextButton} onClick={() => setStep(3)} title="Next" />
                </>
              )}
              {step === 3 && (
                <>
                  <Image 
                    src={`/images/onboarding/brain.svg`} 
                    alt="brain icon" 
                    width={150} 
                    height={150} 
                    className={styles.featureIcons}
                  />
                  <h2 className={styles.features}>Mindfulness and<br />Meditation Exercises</h2>
                  <p className={styles.featuresText}>Explore quick and calming <br />mindfulness and meditation <br /> exercises, links, and videos</p>
                  <DottedProgressBar currentStep={step} />
                  <ButtonLong className={styles.nextButton} onClick={() => setStep(4)} title="Next" />
                </>
              )}
              {step === 4 && (
                <>
                  <Image 
                    src={`/images/onboarding/logo.svg`} 
                    alt="Logo icon" 
                    width={150} 
                    height={150} 
                    className={styles.logoIcon}
                  />
                  <h2 className={styles.startJourneyText}>Are you ready to start <br /> your journey?</h2>
                  <div>
                    <input 
                      id="inputName" 
                      className={styles.nameInput}
                      type="text" 
                      value={inputName} 
                      onChange={handleInputChange} 
                      placeholder="Enter your name" 
                    />
                    {nameValid && <p className={styles.requiredName}>*{nameValid}</p>}
                  </div>
                  <ButtonLong 
                    className={styles.goButton} 
                    onClick={goClick} 
                    disabled={!inputName.trim()}
                    title="Let's Go!"
                  />
                </>
              )}
              {step === 5 && (
                <div className={styles.createProfilecontainer}>
                  <div className={styles.createProfile}>Select a Profile Avatar</div>
                  <div className={styles.yourName}>{inputName}</div>
                  <div className={styles.chosenIcon}>
                    <Image 
                      src={chosenIcon} 
                      alt="Chosen Icon" 
                      width={150} 
                      height={150} 
                      className={styles.onboardingIcon}
                    />
                  </div>
                  <div className={styles.iconContainer}>
                    <div className={styles.iconBox} onClick={() => handleIconClick("/images/onboarding/option1.svg")}>
                      <Image 
                        src={`/images/onboarding/option1.svg`} 
                        alt="Option 1" 
                        width={150} 
                        height={150} 
                        className={styles.onboardingIcon}
                      />
                    </div>
                    <div className={styles.iconBox} onClick={() => handleIconClick("/images/onboarding/option2.svg")}>
                      <Image 
                        src={`/images/onboarding/option2.svg`} 
                        alt="Option 2" 
                        width={150} 
                        height={150} 
                        className={styles.onboardingIcon}
                      />
                    </div>
                    <div className={styles.iconBox} onClick={() => handleIconClick("/images/onboarding/option3.svg")}>
                      <Image 
                        src={`/images/onboarding/option3.svg`} 
                        alt="Option 3" 
                        width={150} 
                        height={150} 
                        className={styles.onboardingIcon}
                      />
                    </div>
                  </div>
                  <ButtonLong className={styles.perfectButton} onClick={perfectClick} title="Perfect"></ButtonLong>
                </div>
              )}
            </div>
          )}
        </div>
      </main>
    </>
  );
}
