import Head from "next/head";
import styles from "@/styles/Home.module.css";
import ButtonPrimary from "@/components/ButtonPrimary";
import ButtonSecondary from "@/components/ButtonSecondary";
import Image from "next/image";
import { useState } from "react";
import Link from "next/link";

export default function Onboarding() {
  const [currentScreen, setCurrentScreen] = useState(0);

  const [chosenIcon, setChosenIcon] = useState(null);
  const [inputName, setInputName] = useState('');

  const getStartedClick = () => {
    setCurrentScreen(1);
  };

  const nextClick = () => {
    if (currentScreen < 4) {
      setCurrentScreen(currentScreen + 1);
    }
  };

  const handleIconClick = (icon) => {
    setChosenIcon(icon);
  };

  const handleInputChange = (e) => {
    setInputName(e.target.value);
  };

  const screen1 = () => (
    <div>
      <Image 
        src={`/images/onboarding/personalize.svg`} 
        alt="personalize icon" 
        width={150} 
        height={150} 
        className={styles.personalizeIcon}
      />
      <h2 className={styles.features}>Personalize your experience</h2>
      <p className={styles.featuresText}>Select and unlock special <br /> icons, and frames</p>
    </div>
  );

  const screen2 = () => (
    <div>
      <Image 
        src={`/images/onboarding/brain.svg`} 
        alt="brain icon" 
        width={150} 
        height={150} 
        className={styles.brainIcon}
      />
      <h2 className={styles.featuresBrain}>Mindfulness and<br />Meditation Exercises</h2>
      <p className={styles.featuresTextBrain}>Explore quick and calming <br />  mindfulness and meditation exercises</p>
    </div>
  );

  const screen3 = () => (
    <div>
      <Image 
        src={`/images/onboarding/calendar.svg`} 
        alt="calendar icon" 
        width={150} 
        height={150} 
        className={styles.calendarIcon}
      />
      <h2 className={styles.featuresCalendar}>Check-In and Rewards</h2>
      <p className={styles.featuresTextCalendar}>Check in on your mental health and <br /> unlock rewards</p>
    </div>
  );

  const screen4 = () => (
    <div className={styles.createProfilecontainer}>
      <div className={styles.createProfile}>Create Profile</div>
      <div className={styles.selectIcon}>Select an Icon</div>
      <div className={styles.chosenIcon} style={{ borderColor: chosenIcon ? 'black' : 'transparent' }}>
        {chosenIcon && (
          <Image 
            src={chosenIcon} 
            alt="Chosen Icon" 
            width={150} 
            height={150} 
            className={styles.onboardingIcon}
          />
        )}
      </div>
      <div className={styles.iconContainer}>
        <div className={styles.iconBox} onClick={() => handleIconClick(`/images/onboarding/option1.svg`)}>
          <Image 
            src={`/images/onboarding/option1.svg`} 
            alt="Option 1" 
            width={150} 
            height={150} 
            className={styles.onboardingIcon}
          />
        </div>
        <div className={styles.iconBox} onClick={() => handleIconClick(`/images/onboarding/option2.svg`)}>
          <Image 
            src={`/images/onboarding/option2.svg`} 
            alt="Option 2" 
            width={150} 
            height={150} 
            className={styles.onboardingIcon}
          />
        </div>
        <div className={styles.iconBox} onClick={() => handleIconClick(`/images/onboarding/option3.svg`)}>
          <Image 
            src={`/images/onboarding/option3.svg`} 
            alt="Option 3" 
            width={150} 
            height={150} 
            className={styles.onboardingIcon}
          />
        </div>
      </div>
      <div onClick={() => document.getElementById('inputName').focus()}>
        <input 
          id="inputName" 
          className={styles.nameInput}
          type="text" 
          value={inputName} 
          onChange={handleInputChange} 
          placeholder="Enter your name" 
        />
      </div>
      <Link href="/">
        <ButtonPrimary className={styles.perfectButton} title="Perfect"></ButtonPrimary>
      </Link>  
    </div>
  );
  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main}`}>
      <div className={`${styles.mainContainer} ${styles.onboardingContainer}`}>
          {currentScreen === 0 && (
            <Image
              src={`/images/onboarding/verticalLogo.svg`}
              alt="vertical logo"
              width={258}
              height={220}
              className={styles.verticalLogo}
            />
          )}
          {currentScreen === 0 && (
            <ButtonPrimary className={styles.getStartedButton} onClick={getStartedClick} title="Get Started"></ButtonPrimary>
          )}
          {currentScreen === 1 && screen1()}
          {currentScreen === 2 && screen2()}
          {currentScreen === 3 && screen3()}
          {currentScreen === 4 && screen4()}
          {currentScreen > 0 && currentScreen < 4 && (
            <ButtonPrimary className={styles.getStartedButton} onClick={nextClick} title="Next"></ButtonPrimary>
          )}
          {currentScreen === 6 && (
            <Link href="/">
              <ButtonPrimary className={styles.getStartedButton} title="Let's Go!"></ButtonPrimary>
            </Link>
          )}
        </div>        
      </main>
    </>
  )
}
