import { useEffect, useState } from 'react';
import Head from 'next/head';
import styles from '@/styles/Home.module.css';
import Navbar from '@/components/Navbar';
import Tabbar from '@/components/Tabbar';
import Image from 'next/image';
import Link from 'next/link';
import ButtonProfile from '@/components/ButtonProfile';
import { useRouter } from "next/router";

export default function Profile() {
  const router = useRouter();
  const [name, setName] = useState('');
  const [icon, setIcon] = useState('');

  useEffect(() => {
    const storedName = localStorage.getItem('inputName');
    const storedIcon = localStorage.getItem('chosenIcon');
    if (storedName && storedIcon) {
      setName(storedName);
      setIcon(storedIcon);
    }
  }, []);

  return (
    <>
      <Head>
        <title>CalmQuest</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.mainContainer}>
          <Navbar />
          <div className={styles.profileContainer}>
            <div className={styles.contentWrapper}>
              {name && icon && (
                <div className={styles.nameContainer}>
                  <div className={styles.profileIcon}>
                    <Image src={icon} alt="Profile Icon" width="185" height="185" />
                  </div>
                  <h1 className={styles.name}>{name}</h1>
                </div>
              )}
              <ButtonProfile className={styles.editProfile} title="Edit Profile" onClick={() => router.push('/EditProfile')}></ButtonProfile>
              <div className={styles.linkButtons}>
                <Link href="/Settings" className={styles.profileLinks}>
                  <div className={styles.settingsContainer}>
                    <Image src={`/images/settings.svg`} alt="settings icon" width={40} height={40} className={styles.profileSettingsIcon} />
                    <div className={styles.settingsText}>Settings</div>
                  </div>
                </Link>
                <Link href="/About" className={styles.profileLinks}>
                  <div className={styles.settingsContainer}>
                    <Image src={`/images/about.svg`} alt="about icon" width={40} height={40} className={styles.profileSettingsIcon} />
                    <div className={styles.settingsAboutText}>About</div>
                  </div>
                </Link>
              </div>
            </div>
          </div>
          <Tabbar />
        </div>
      </main>
    </>
  );
}
