import Head from "next/head";
import styles from "@/styles/Home.module.css";
import Tabbar from "@/components/Tabbar";
import Navbar from "@/components/Navbar";
import Image from "next/image";
import { useRouter } from "next/router";
import ButtonRegular from "@/components/ButtonRegular";

export default function Profile() {
    const router = useRouter();
    const { name, icon } = router.query;

    return(
        <>
            <Head>
                <title>CalmQuest</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={`${styles.main}`}>
                <div className={styles.mainContainer}>
                    <Navbar/>
                    <div className={styles.profileContainer}>
                        {icon && (
                            <div className={styles.nameContainer}>
                                <div className={styles.profileIcon}>
                                    <Image 
                                        src={icon} 
                                        alt="Profile Icon" 
                                        width="112" 
                                        height="112" 
                                        className={styles.profileIcon} 
                                    />
                                </div>
                                <h1 className={styles.name}>{name}</h1>
                                <div className={styles.editName}>Edit Name</div>
                            </div>
                        )}
                        <ButtonRegular className={styles.customizeButton} title="Customize" onClick={() => router.push('/ChangeProfile')}></ButtonRegular>
                        <Image
                            src={`/images/mascots/mascotUWU.svg`}
                            alt="profile UWU mascot"
                            width="177"
                            height="262"
                            className={styles.mascotProfilePage}
                        />
                    </div>
                    <Tabbar/>
                </div>
            </main>
        </>
    )
}