import Navbar from "@/components/Navbar";
import Tabbar from "@/components/Tabbar";
import Link from "next/link";
import styles from '@/styles/Home.module.css';
import Head from "next/head";
import Image from "next/image";


export default function Contact() {
    return(
        <>
            <Head>
				<title>Contact</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
            <main className={`${styles.main}`}>
                <div className={styles.mainContainer}>
                    <Navbar/>
                    <div className={styles.goBackProfile}>
                            <Link href="/Profile" className={styles.goBackLink}>
                                <Image src="/images/leftArrow.svg" className={styles.leftArrow} width={15} height={15}/>
                                Go Back
                            </Link>
                        </div>
                    <div className={styles.headingContainer}>
                        <h2 className={styles.h2Settings}>
                        Settings 
                        </h2>
                    </div>
                    <Link href="/Languages" className={styles.changeLanguageContainer}>
                        <h3 className={styles.changeLangH3}>Change Language</h3>
                    </Link>
                <Tabbar/>
                </div>
            </main>
        </>
    );
}